# contents
nav:
  - Home:
      - Index: index.md
      - Hoge: hoge.md

# metadata
site_name: MkDocs Test Site
docs_dir: src
use_directory_urls: false

# theme
theme:
  name: material
  language: en
